elife:
    key: 1d29e6b3-1b74-467d-b2a6-cd3107e674d2
    keyHeader: X-API-KEY


logging:
  level:
    root: INFO
    '[org.springframework.security]': DEBUG
    '[org.springframework.boot.autoconfigure]': DEBUG
    '[com.elife.connect]': TRACE
    '[com.keycloak.elife.connect.config]': TRACE
  file:
    name: elife-connect.log
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
     