spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://124.43.199.226:8085/realms/liclanka-prod
          jwk-set-uri: http://124.43.199.226:8085/realms/liclanka-prod/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://124.43.199.226:8085/realms/liclanka-prod
            token-uri: http://124.43.199.226:8085/realms/liclanka-prod/protocol/openid-connect/token
            authorization-uri: http://124.43.199.226:8085/realms/liclanka-prod/protocol/openid-connect/auth
            user-info-uri: http://124.43.199.226:8085/realms/liclanka-prod/protocol/openid-connect/userinfo
            jwk-set-uri: http://124.43.199.226:8085/realms/liclanka-prod/protocol/openid-connect/certs
        registration:
          kenya-portal-client:
            provider: keycloak
            clientId: lanka-portal-client
            clientSecret: AduQvfB8jpYkAYyUqhegSMQ2dylsMuW5
            authorizationGrantType: client_credentials
            clientAuthenticationMethod: client_secret_basic
            scope: openid,profile,email,roles
          ui-client:
            provider: keycloak
            clientId: spring-ui-client
            clientSecret: Jx8vbiyRGigvJjUCJeWB8sEhOue8v0xD
            authorizationGrantType: authorization_code
            clientAuthenticationMethod: client_secret_basic
            scope: openid,profile,email,roles
            redirectUri: http://124.43.199.226:8085/login/oauth2/code/keycloak
  datasource:
      url: jdbc:mysql://192.168.0.100:3306/lanka?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      username: elifeconnect
      password: devFeap@123
      driver-class-name: com.mysql.cj.jdbc.Driver

      hikari:
        maximum-pool-size: 20
        minimum-idle: 5
        pool-name: eLifeConnectApiHikariCP
        connection-timeout: 30000      # 30 sec
        idle-timeout: 600000           # 10 min
        max-lifetime: 1800000          # 30 min
        validation-timeout: 5000
        leak-detection-threshold: 20000

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none               # Use 'none' in PROD

    show-sql: false
    properties:
      hibernate:
        '[format_sql]': true         # Clean, warning-free escaping
        jdbc:
          '[time_zone]': UTC
        '[globally_quoted_identifiers]': true
      
        
elife:
  api:
    baseurl: http://192.168.0.33:8080/eLife/elifeRestServices