server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

spring:
  profiles:
    active: kenya-dev

elife:
  api:
    baseurl:
    key: 1d29e6b3-1b74-467d-b2a6-cd3107e674d2
    keyHeader: X-API-KEY

    gp:
      member:
        statement:
          url: /api/v1/gp/member/statement
        record:
          card:
            url: /api/v1/gp/member/record/card
        fund:
          summary:
            url: /api/v1/gp/member/fund/summary
        details:
          url: /api/v1/gp/member/details
      trustee:
        details:
          url: /api/v1/gp/trustee/details

      scheme:
        fund:
          balance:
            url: /api/v1/gp/scheme/fund/balance
        profile:
          url: /api/v1/gp/scheme/profile
          information:
            url: /api/v1/gp/scheme/profile/information

        admin:
          url: /api/v1/gp/scheme/admin

        pensioner:
          url: /api/v1/gp/scheme/pensioner
        details:
          url: /api/v1/gp/scheme/details
        member:
          details:
            url: /api/v1/gp/scheme/member/details

    loan:
      enquiry:
        url: /online/loan/enquiry
      repayment:
        letter:
          url: /api/v1/loan/repayment/letter
      quotation:
        url: /api/v1/loan/quotation

    customer:
      authentication:
        url: /api/Authentication/v1/client

    agent:
      authentication:
        url: /api/Authentication/v1/agent
      commission:
        statement:
          url: /api/v1/commission/statement

    employee:
      authentication:
        url: /api/Authentication/v1/employee

    plan:
      details:
        url: /online/v1/plan/details

    premium:
      renewal:
        enquiry:
          url: /policyEnquiry
        adjustment:
          url: /adjustAmount
      statement:
        full:
          url: /api/v1/premium/statement/full
      summary:
        url: /api/v1/premium/summary

    policy:
      details:
        url: /api/v1/policy/details
      customer:
        enquiry:
          url: /api/v1/policy/enquiry/customer
      agent:
        enquiry:
          url: /api/v1/policy/enquiry/agent
      revival:
        quotation:
          url: /online/polrev

    proposal:
      premium:
        enquiry:
          url: /api/v1/proposal/premium/enquiry
      submission:
        enquiry:
          url: /api/v1/online/proposal/enquiry
      submit:
        url: /online/proposal/submit
      deposit:
        creation:
          url: /online/proposaldeposit/create

    ulip:
      fund:
        position:
          single:
            url: /online/fundstat
